// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUJgRBsFU2UQOV0tmD2gv-qxgHJWwzhQQ',
    appId: '1:666679333553:web:96706431b92703a52e8890',
    messagingSenderId: '666679333553',
    projectId: 'easyshopping-4fea5',
    authDomain: 'easyshopping-4fea5.firebaseapp.com',
    storageBucket: 'easyshopping-4fea5.firebasestorage.app',
    measurementId: 'G-D937ZYWBKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTG-z1mD1D-8lYk0YXzvFB3RWls5ZfIqU',
    appId: '1:666679333553:android:5f392d80aeef42742e8890',
    messagingSenderId: '666679333553',
    projectId: 'easyshopping-4fea5',
    storageBucket: 'easyshopping-4fea5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSOH0eFC5wC-i39x-fiKkENOtUC0qust4',
    appId: '1:666679333553:ios:f7eceac478a3d38d2e8890',
    messagingSenderId: '666679333553',
    projectId: 'easyshopping-4fea5',
    storageBucket: 'easyshopping-4fea5.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSOH0eFC5wC-i39x-fiKkENOtUC0qust4',
    appId: '1:666679333553:ios:f7eceac478a3d38d2e8890',
    messagingSenderId: '666679333553',
    projectId: 'easyshopping-4fea5',
    storageBucket: 'easyshopping-4fea5.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUJgRBsFU2UQOV0tmD2gv-qxgHJWwzhQQ',
    appId: '1:666679333553:web:3e21c1faf84ec9912e8890',
    messagingSenderId: '666679333553',
    projectId: 'easyshopping-4fea5',
    authDomain: 'easyshopping-4fea5.firebaseapp.com',
    storageBucket: 'easyshopping-4fea5.firebasestorage.app',
    measurementId: 'G-KZP1S9RS8K',
  );
}
